
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[jwt]
  expireduration = 24
  secret = "i1ydX9RtHyuJTrw7frcu"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "192.168.199.230:3306"
    name = "mikemall"
    pass = "123456"
    user = "mall"

  [mysql.write]
    addr = "192.168.199.230:3306"
    name = "mikemall"
    pass = "123456"
    user = "mall"

[redis]
  addr = "192.168.199.230:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = ""
  poolsize = 10

[urltoken]
  expireduration = 10
  secret = "i1ydX9RtHyuJTrw7frcu"
